export { default as Home } from './Home'
export { default as Diluc } from './Diluc'
export { default as Albedo } from './Albedo'
export { default as Fischl } from './Fischl'
export { default as Qiqi } from './Qiqi'
export { default as Venti } from './Venti'
export { default as Ganyu } from './Ganyu'
export { default as Zhongli } from './Zhongli'